# Generated by Django 3.2.4 on 2021-06-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpost',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
